In [152]:
import numpy as np
import math
import csv
csv_reader = csv.reader(open("11.csv"))
count=0
angle3=[0,0,0,0,0]
diff=0
wr_tmp=[0,0,0]
ang3_tmp1=0
ang3_tmp2=0
with open('csv_file.csv', 'w') as f:
    writer = csv.writer(f)
    for file in csv_reader:
       # file=float(file)
        #file=np.asarray(file)
        count+=1
        P_hip=[file[0],file[1],file[2]];  
        P_ne=[file[3],file[4],file[5]];  
        P_sh_l=[file[6],file[7],file[8]]; 
        P_shoulder=[file[9],file[10],file[11]];  
        P_elbow=[file[12],file[13],file[14]];  
        P_wrist=[file[15],file[16],file[17]];    

        P_hip=[float(P_hip[i]) for i in range(len(P_hip))];
        P_ne=[float(P_ne[i]) for i in range(len(P_ne))];
        P_sh_l=[float(P_sh_l[i]) for i in range(len(P_sh_l))];
        P_shoulder=[float(P_shoulder[i]) for i in range(len(P_shoulder))];
        P_elbow=[float(P_elbow[i]) for i in range(len(P_elbow))];
        P_wrist=[float(P_wrist[i]) for i in range(len(P_wrist))];


        P_se = np.asarray([float(P_elbow[i]) - float(P_shoulder[i]) for i in range(len(P_shoulder))])
        P_sw = np.asarray([float(P_wrist[i]) - float(P_shoulder[i]) for i in range(len(P_shoulder))]);
        P_lr = np.asarray([float(P_shoulder[i]) - float(P_sh_l[i]) for i in range(len(P_shoulder))]);
        B = np.asarray([float(P_wrist[i]) - float(P_elbow[i]) for i in range(len(P_shoulder))]);
        A = np.asarray([float(P_shoulder[i]) - float(P_elbow[i]) for i in range(len(P_shoulder))]);




        x_axis= P_lr/np.sqrt(P_lr.dot(P_lr))
        y_axis=np.cross(x_axis,np.asarray([P_hip[i] - P_shoulder[i] for i in range(len(P_shoulder))]))
        y_axis= y_axis/np.sqrt(y_axis.dot(y_axis)) 
        z_axis=np.cross(x_axis,y_axis);
        z_axis= z_axis/np.sqrt(z_axis.dot(z_axis))

        TT=np.array([x_axis,y_axis,z_axis])

        P_se2=np.dot(TT,P_se)


        if abs(P_se2[0])< 10e-5:
            P_se2[0]=0;

        if abs(P_se2[1])< 10e-5:
            P_se2[1]=0;

        if abs(P_se2[2])< 10e-5:
            P_se2[2]=0;


        alpha_shoulder = math.atan2(P_se2[1],P_se2[0])
        if alpha_shoulder == 0:
            P_sw2=np.dot(TT,P_sw)
            alpha_shoulder = math.atan2(P_sw2[1],P_sw2[0])

        alpha_shoulder_d = alpha_shoulder * 180 / math.pi

        beta_shoulder = math.atan2(P_se2[2],math.sqrt(P_se2[1]**2+P_se2[0]**2))+ math.pi/2; 
        beta_shoulder_d = beta_shoulder * 180 / math.pi

        elbow_ang=math.acos(np.dot(A / np.linalg.norm(A),B / np.linalg.norm(B)))
        elbow_ang_d=elbow_ang * 180 / math.pi


        P_wrist=np.dot(TT,P_wrist)
        P_elbow=np.dot(TT,P_elbow)

        len_f=np.linalg.norm(B)

        angle3[4]=count
        gamma_shoulder1=0
        gamma=0
        if beta_shoulder ==0 or elbow_ang==0:
            gamma_shoulder=math.acos((math.cos(beta_shoulder)*math.cos(elbow_ang)));
          #  angle3[2]=gamma_shoulder.real*180/math.pi
            gamma=gamma_shoulder.real*180/math.pi
            ang3_tmp2=gamma_shoulder.real
           # angle3[3]=0
        else:
            #if count>1:
            a=(math.cos(beta_shoulder)*math.cos(elbow_ang)-((P_wrist[2]-P_elbow[2])/len_f)/math.sin(beta_shoulder)/math.sin(elbow_ang))
            if a>1 or a<-1:
                gamma_shoulder1= math.pi/2
            else:
                gamma_shoulder1= math.acos(a)-math.pi/2
          #  angle3[0]=gamma_shoulder1.real*180/math.pi

            gamma_shoulder2=gamma_shoulder1

            if count>1:
                diff=abs(gamma_shoulder2 - ang3_tmp1);
                if diff*180/math.pi>2:
                    diff=0;

              #  angle3[1]=diff*180/math.pi;

                if P_wrist[0]<=wr_tmp[0]:
                    gamma_shoulder3= ang3_tmp2+diff;
                #    angle3[2]=gamma_shoulder3.real*180/math.pi
             #       angle3[3]=1;
                else:
                    gamma_shoulder3= ang3_tmp2-diff;
                  #  angle3[2]=gamma_shoulder3.real*180/math.pi
             #       angle3[3]=2;
                ang3_tmp2=gamma_shoulder3.real
                gamma=gamma_shoulder3.real
                gamma_d=gamma_shoulder3.real*180/math.pi
        ang3_tmp1=gamma_shoulder1.real
        wr_tmp=P_wrist

        print(gamma_d,count)
        
        row=[alpha_shoulder_d,beta_shoulder_d,elbow_ang_d,gamma_d]
        writer.writerow(row)
    
   
  #  print(count)


89.9995929275015 1
89.9995929275015 2
89.9995929275015 3
89.9995929275015 4
89.9995929275015 5
89.9995929275015 6
89.9995929275015 7
89.9995929275015 8
89.9995929275015 9
89.9995929275015 10
89.9995929275015 11
89.9995929275015 12
89.9995929275015 13
89.9995929275015 14
89.9995929275015 15
89.9995929275015 16
89.9995929275015 17
89.9995929275015 18
89.9995929275015 19
89.9995929275015 20
89.9995929275015 21
89.9995929275015 22
89.9995929275015 23
89.9995929275015 24
89.9995929275015 25
89.9995929275015 26
89.9995929275015 27
89.9995929275015 28
89.9995929275015 29
89.9995929275015 30
89.9995929275015 31
89.9995929275015 32
89.9995929275015 33
89.9995929275015 34
89.9995929275015 35
89.9995929275015 36
89.9995929275015 37
89.9995929275015 38
89.9995929275015 39
89.9995929275015 40
89.9995929275015 41
89.9995929275015 42
89.9995929275015 43
89.9995929275015 44
89.9995929275015 45
89.9995929275015 46
89.9995929275015 47
89.9995929275015 48
89.9995929275015 49
89.9995929275015 50
89.999592

90.00016315565775 796
90.00016315565775 797
90.00016315565775 798
90.00016315565775 799
90.00016315565775 800
90.00016315565775 801
90.00016315565775 802
90.00016315565775 803
90.00016315565775 804
90.00016315565775 805
90.00016315565775 806
90.00016315565775 807
90.00016315565775 808
90.00016315565775 809
90.00016315565775 810
90.00016315565775 811
90.00016315565775 812
90.00016315565775 813
90.00016315565775 814
90.00016315565775 815
90.00016315565775 816
90.00016315565775 817
90.00016315565775 818
90.00016315565775 819
90.00016315565775 820
90.00016315565775 821
90.00016315565775 822
90.00016315565775 823
90.00016315565775 824
90.00016315565775 825
90.00016315565775 826
90.00016315565775 827
90.00016315565775 828
90.00016315565775 829
90.00016315565775 830
90.00016315565775 831
90.00016315565775 832
90.00016315565775 833
90.00016315565775 834
90.00016315565775 835
90.00016315565775 836
90.00016315565775 837
90.00016315565775 838
90.00016315565775 839
90.00016315565775 840
90.0001631

89.9995929275015 1600


In [99]:
TT

array([[ 1.,  0.,  0.],
       [-0.,  1.,  0.],
       [ 0., -0.,  1.]])

In [135]:
math.acos(2).real

ValueError: math domain error

In [78]:
zz=np.mat([x_axis,y_axis,z_axis]).T
print(zz)
zz[0,0]

[[ 0.94025582 -0.08027488  0.33086996]
 [ 0.19985754  0.91689165 -0.3454948 ]
 [-0.27563736  0.39098036  0.87815626]]


0.9402558215593767

In [47]:
A.T

array([-6.18541175,  7.72425236, -5.30404177])

In [49]:
axis_x


NameError: name 'axis_x' is not defined